# Generated by Django 4.1.5 on 2023-01-26 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_rename_menu_menuitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='boking_date',
            new_name='booking_date',
        ),
    ]
